# -*- coding: utf-8 -*-
"""EuropeanFootballAnalysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sUECUKzv9KL2Jh1DtOOHX90FH2kvNeRU
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import numpy as np
from bs4 import BeautifulSoup
import matplotlib.pyplot as plt

class EuropeanFootballAnalysis:
    def __init__(self, filename="Player_Stats.html"):
        self.file = filename
        self.raw_data = None
        self.cleaned_data = None

        self.position_map = {
            'GK': 'Goalkeeper',
            'DF': 'Defender',
            'MF': 'Midfielder',
            'FW': 'Forward'
        }

        self.colors = {
            'Premier League': '#38003c',
            'La Liga': '#eda132',
            'Bundesliga': '#d3010c',
            'Serie A': '#008fd8',
            'Ligue 1': '#091c3e'
        }

        self.team_colors = {
            'Manchester City': '#6CABDD',
            'Arsenal': '#EF0107',
            'Liverpool': '#C8102E',
            'Manchester United': '#DA291C',
            'Tottenham': '#FFFFFF',
            'Chelsea': '#034694',
            'Newcastle United': '#241F20',
            'Brighton': '#0057B8',
            'Aston Villa': '#95BFE5',
            'West Ham': '#7A263A',

            'Real Madrid': '#FEBE10',
            'Barcelona': '#A50044',
            'Atletico Madrid': '#CB3524',
            'Sevilla': '#FFFFFF',
            'Real Betis': '#00954C',
            'Villarreal': '#FFE667',
            'Real Sociedad': '#00529F',
            'Athletic Club': '#EE2523',

            'Inter': '#010E80',
            'Milan': '#FB090B',
            'Juventus': '#000000',
            'Napoli': '#12A0D7',
            'Roma': '#8E1F2F',
            'Lazio': '#FFFFFF',
            'Atalanta': '#1D5EA8',
            'Fiorentina': '#482E92',

            'Bayern Munich': '#0066B3',
            'Dortmund': '#FDE100',
            'RB Leipzig': '#DD0741',
            'Leverkusen': '#E32219',
            'Eintracht Frankfurt': '#E21A23',
            'Wolfsburg': '#65FF00',
            'Freiburg': '#E30613',
            "M'Gladbach": '#000000',

            'Paris S-G': '#004170',
            'Marseille': '#00B9F1',
            'Lyon': '#D61C28',
            'Monaco': '#E30613',
            'Lille': '#E21A23',
            'Rennes': '#E21A23',
            'Lens': '#FFDC00',
            'Nice': '#000000'
        }

    def scrape(self):
        with open(self.file, "r", encoding="utf-8") as f:
            html = f.read()

        page = BeautifulSoup(html, "lxml")

        table = None
        for t in page.find_all("table"):
            cap = t.find("caption")
            if cap and "Player Standard Stats" in cap.get_text():
                table = t
                break

        if table is None:
            raise ValueError("Player Standard Stats table not found")

        thead = table.find("thead")
        header_rows = thead.find_all("tr")
        headers = [th.get_text() for th in header_rows[-1].find_all(["th", "td"])]

        rows = []
        tbody = table.find("tbody")
        for tr in tbody.find_all("tr"):
            if tr.get("class") and "thead" in tr.get("class"):
                continue

            cells = [c.get_text() for c in tr.find_all(["th", "td"])]
            if not cells:
                continue

            if len(cells) > len(headers):
                cells = cells[-len(headers):]
            if len(cells) < len(headers):
                cells += [""] * (len(headers) - len(cells))

            rows.append(cells)

        self.raw_data = pd.DataFrame(rows, columns=headers)
        return self.raw_data

    def clean_data(self):
      if self.raw_data is None:
        self.scrape()
      df = self.raw_data.copy()

      df = df.loc[:, ~df.columns.duplicated()]
      df.replace("", np.nan, inplace=True)

      if "Nation" in df.columns:
        df["Nation"] = df["Nation"].astype(str).str.extract(r"([A-Z]{3})", expand=False)

      if "Comp" in df.columns:
        df["League"] = df["Comp"].astype(str).str.replace(r"^[a-z]{2}\s+", "", regex=True)

      if "Pos" in df.columns:
        df["Primary_Position"] = df["Pos"].astype(str).apply(self._extract_primary_position)

      if "Min" in df.columns:
        df["Min"] = pd.to_numeric(df["Min"].astype(str).str.replace(",", "", regex=False), errors="coerce")

      text_cols = ["Player", "Squad", "Comp", "League", "Pos", "Primary_Position", "Nation"]

      for c in df.columns:
        if c not in text_cols:
            df[c] = pd.to_numeric(df[c], errors="coerce")

      df.fillna(0, inplace=True)

      self.cleaned_data = df
      return self.cleaned_data



    def _extract_primary_position(self, pos_str):
        s = str(pos_str)
        if "," in s:
          s = s.split(",")[0]
        for p in ["GK", "DF", "MF", "FW"]:
          if s.startswith(p):
            return p
        return "Unknown"

    def add_derived_metrics(self):
        df = self.cleaned_data.copy()
        df["Minutes_per_Game"] = np.where(df["MP"] > 0, df["Min"] / df["MP"], 0)

        if "G+A" in df.columns:
            ga = pd.to_numeric(df["G+A"], errors="coerce").fillna(0)
        else:
            ga = pd.to_numeric(df.get("Gls", 0), errors="coerce").fillna(0) + pd.to_numeric(df.get("Ast", 0), errors="coerce").fillna(0)

        df["Goal_Contribution_Rate"] = np.where(df["90s"] > 0, ga / df["90s"], 0)
        self.cleaned_data = df
        return self.cleaned_data

    def find_top_scorer(self):
        df = self.cleaned_data
        m = df["Gls"].max()
        return df.loc[df["Gls"] == m, ["Player", "Squad", "Gls", "League"]]

    def find_playmaker(self):
        df = self.cleaned_data
        m = df["Ast"].max()
        return df.loc[df["Ast"] == m, ["Player", "Squad", "Ast", "League"]]

    def find_ironman(self):
        df = self.cleaned_data
        m = df["Min"].max()
        return df.loc[df["Min"] == m, ["Player", "Squad", "Min", "MP"]]

    def find_efficient_striker(self):
        df = self.cleaned_data
        d = df[(df["Primary_Position"] == "FW") & (df["Min"] > 1000)].copy()
        d["Goals_per_Minute"] = np.where(d["Min"] > 0, d["Gls"] / d["Min"], 0)
        m = d["Goals_per_Minute"].max()
        return d.loc[d["Goals_per_Minute"] == m, ["Player", "Squad", "Gls", "Min", "Goals_per_Minute"]]

    def find_most_disciplined(self):
        df = self.cleaned_data
        d = df[df["Min"] > 1000].copy()
        d["Discipline_Score"] = np.where(d["90s"] > 0, (d.get("CrdY", 0) + d.get("CrdR", 0)) / d["90s"], 0)
        m = d["Discipline_Score"].max()
        return d.loc[d["Discipline_Score"] == m, ["Player", "Squad", "CrdY", "CrdR", "Discipline_Score", "Primary_Position"]]

    def data_quality_report(self):
      df = self.cleaned_data if self.cleaned_data is not None else self.raw_data
      missing = df.isna().sum()
      dp_players = df["Player"].value_counts()
      dp_players = dp_players[dp_players > 1]
      return missing, dp_players

    def handle_transfers(self):
      df = self.cleaned_data.copy()

      transferred = df[df["Player"].duplicated(keep=False)]
      sum_cols = ["Min", "MP", "Starts", "Gls", "Ast", "G+A", "CrdY", "CrdR"]
      sum_cols = [c for c in sum_cols if c in df.columns]

      rate_cols = [c for c in df.columns if "/90" in c]

      agg = {c: "sum" for c in sum_cols}
      agg.update({c: "mean" for c in rate_cols})
      agg.update({c: "first" for c in df.columns if c not in agg})

      result = transferred.groupby("Player", as_index=False).agg(agg)
      return result

class1 = EuropeanFootballAnalysis()
class1.scrape()
df = class1.clean_data()

df[["Pos", "Primary_Position"]].head(50)

pd.set_option("display.max_columns", None)
class1 = EuropeanFootballAnalysis()
class1.scrape()
df = class1.clean_data()
df.head(100)

pd.set_option("display.max_columns", None)

pd.set_option("display.max_rows", None)
df

df[df.isna().any(axis=1)]

class1 = EuropeanFootballAnalysis()

class1.scrape()          # load raw_data
class1.clean_data()      # clean + prepare data
class1.add_derived_metrics()  # add calculated columns

class1.find_top_scorer()

class1.find_playmaker()

class1.find_ironman()

class1.find_efficient_striker()

class1.find_most_disciplined()

class1 = EuropeanFootballAnalysis()
class1.scrape()
class1.clean_data()

transfers = class1.handle_transfers()
transfers.head()

missing, dup_players = class1.data_quality_report()
missing, dup_players.head()